GET http://127.0.0.1:3000/api/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTNhODFkOWRlY2I1ZTc1NGQ0ZGYzYSIsInJvbGUiOiJyZWd1bGFyIiwiaWF0IjoxNzEyNTc1MjM3fQ.KVH_NmYDbH531PGvKfjlKETmCxnWjbxpj95PXJFvYfQ

###
GET http://127.0.0.1:3000/api/products/active
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTNhODFkOWRlY2I1ZTc1NGQ0ZGYzYSIsInJvbGUiOiJyZWd1bGFyIiwiaWF0IjoxNzEyNTc1MjM3fQ.KVH_NmYDbH531PGvKfjlKETmCxnWjbxpj95PXJFvYfQ

###
POST http://127.0.0.1:3000/api/products
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTRmODhjOGNjOTY5YzRjZTc2ZjBlMCIsInJvbGUiOiJyZWd1bGFyIiwiaWF0IjoxNzEyNjUwMzk1fQ.2bh7mva_-TPJy4Hvq7MCiHcFI54dl0XF3Er9xXTUu0o

{ 
    "name": "sartenes",
    "description": "acero inoxidable",
    "price": 45,
    "department": "hogar",
    "available": true,
    "stock": 50
}

###
GET http://localhost:3000/api/products/price/50/max/60
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTNhODFkOWRlY2I1ZTc1NGQ0ZGYzYSIsInJvbGUiOiJyZWd1bGFyIiwiaWF0IjoxNzEyNTc1MjM3fQ.KVH_NmYDbH531PGvKfjlKETmCxnWjbxpj95PXJFvYfQ

###
POST https://pruebatien.onrender.com/api/users/register
Content-Type: application/json

{
    "name": "Logan",
    "email": "logan@gmail.com",
    "password": "12345"
}

###
POST http://localhost:3000/api/users/login
Content-Type: application/json

{
    "email": "logan@gmail.com",
    "password": "12345"
}

###
PUT http://localhost:3000/api/products/add_cart
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTNhODFkOWRlY2I1ZTc1NGQ0ZGYzYSIsInJvbGUiOiJyZWd1bGFyIiwiaWF0IjoxNzEyNTc2NTQxfQ.3sIIpy8vxcU2rvhTcCvWTe_e9jsz4lpHmKVSRvXfWtI

{
    "product_id": "6565d2d08c270fdedef39568"
}


###
GET http://localhost:3000/api/users/profile
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTNhODFkOWRlY2I1ZTc1NGQ0ZGYzYSIsInJvbGUiOiJyZWd1bGFyIiwiaWF0IjoxNzEyNTc2NTQxfQ.3sIIpy8vxcU2rvhTcCvWTe_e9jsz4lpHmKVSRvXfWtI

###
GET http://localhost:3000/api/users/products
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2MTRmODhjOGNjOTY5YzRjZTc2ZjBlMCIsInJvbGUiOiJyZWd1bGFyIiwiaWF0IjoxNzEyNjUwMzk1fQ.2bh7mva_-TPJy4Hvq7MCiHcFI54dl0XF3Er9xXTUu0o